---
abstract: 'O(1) Routing engine for web applications'
author:
  - 'tokuhirom <tokuhirom@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.7.5, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Router-Boom
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Router::Boom:
    file: lib/Router/Boom.pm
    version: 0.01
  Router::Boom::Compiled:
    file: lib/Router/Boom/Compiled.pm
  Router::Boom::Node:
    file: lib/Router/Boom/Node.pm
requires:
  Moo: 1.003001
  perl: 5.008005
resources:
  bugtracker: https://github.com/tokuhirom/Router-Boom/issues
  homepage: https://github.com/tokuhirom/Router-Boom
  repository: git://github.com/tokuhirom/Router-Boom.git
version: 0.01
